#哈啰智能芯
binary_sensor:
  - platform: rest
    name: 哈啰智能芯状态
    unique_id: hellobike_lockstatus
    resource: https://a.hellobike.com/evehicle/api?rent.order.getRentBikeStatus
    method: POST
    payload: '{"bikeNo" : "xxx","token" : "xxx","action" : "rent.order.getRentBikeStatus"}'
    value_template: '{{ value_json.data.lockStatus }}'
    device_class: lock
sensor:
  - platform: rest
    name: 哈啰智能芯电量
    unique_id: hellobike_battery
    resource: https://a.hellobike.com/evehicle/api?rent.order.getRentBikeStatus
    method: POST
    payload: '{"bikeNo" : "xxx","token" : "xxx","action" : "rent.order.getRentBikeStatus"}'
    value_template: '{{ value_json.data.batteryPercent }}'
    device_class: battery
    unit_of_measurement: '%'
rest_command:
  close_lock:
    url: https://a.hellobike.com/evehicle/api?rent.order.closeLockCommand
    method: POST
    payload: '{"bikeNo" : "xxx","token" : "xxx","action" : "rent.order.closeLockCommand"}'
    content_type: 'application/json; charset=utf-8'
  open_lock:
    url: https://a.hellobike.com/evehicle/api?rent.order.openLock
    method: POST
    payload: '{"bikeNo" : "xxx","token" : "xxx","action" : "rent.order.openLock"}'
    content_type: 'application/json; charset=utf-8'

lock:
  - platform: template
    name: 哈啰智能芯
    unique_id: hellobike_lock
    value_template: "{{ is_state('binary_sensor.hellobike_lockstatus', 'off') }}"
    optimistic: true
    lock:
      service: rest_command.close_lock
    unlock:
      service: rest_command.open_lock
